name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.4.0
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.3.0
  http: ^1.2.2
  rxdart: ^0.27.5
  google_maps_webservice:
    git: 
      url: https://github.com/Khandakar227/google_maps_webservice.git
      ref: 401d427530c03eacf9e64f549fe7925435bbbd83

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
